/* Unity IL2CPP Runtime Dumper - Objective-C / UIKit
 * ARC required. Runtime enumeration uses exported il2cpp_* APIs via dlsym.
 * Only reports data the target runtime actually exposes; method addresses are omitted by default.
 */
#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <QuartzCore/QuartzCore.h>
#import <dlfcn.h>
#import <dispatch/dispatch.h>

#define IL2(name, ret, ...) typedef ret (*name)(__VA_ARGS__)
IL2(DomainGet, void*, void); IL2(DomainAssemblies, void**, void*, size_t*); IL2(AssemblyImage, void*, void*);
IL2(ImageName, const char*, void*); IL2(ImageClassCount, size_t, void*); IL2(ImageClass, void*, void*, size_t);
IL2(ClassName, const char*, void*); IL2(ClassNamespace, const char*, void*); IL2(ClassFields, void*, void*, void**);
IL2(FieldName, const char*, void*); IL2(FieldOffset, size_t, void*); IL2(FieldType, void*, void*); IL2(TypeName, char*, void*); IL2(FieldFlags, uint32_t, void*); IL2(TypeFree, void, char*);
IL2(ClassMethods, void*, void*, void**); IL2(MethodName, const char*, void*); IL2(MethodParamCount, uint32_t, void*);
static void *sym(const char *n){ return dlsym(RTLD_DEFAULT,n); }
static NSString *S(const char *s){ return s ? [NSString stringWithUTF8String:s] : @"?"; }
static BOOL systemAssembly(NSString *n){
 NSString *x=n.lowercaseString;
 // Do not exclude UnityEngine assemblies wholesale: game types may derive from them.
 NSArray *bad=@[@"system.",@"system",@"mscorlib",@"netstandard",@"mono.",@"ms.internal",@"newtonsoft",@"google.",@"facebook.",@"unity.services.",@"unity.timeline"];
 for(NSString *b in bad) if([x hasPrefix:b]) return YES;
 return NO;
}

@interface UnityDumper : UIView <UITextFieldDelegate>
@property UIView *panel,*header,*content; @property UIButton *mini; @property UITextField *search; @property UITextView *output; @property UILabel *status; @property NSMutableString *dump; @property BOOL minimized; @property CGFloat startY;
@end
@implementation UnityDumper
- (UIColor*)blue { return [UIColor colorWithRed:.15 green:.55 blue:1 alpha:1]; }
- (UIButton*)btn:(NSString*)t { UIButton*b=[UIButton buttonWithType:UIButtonTypeSystem]; [b setTitle:t forState:UIControlStateNormal]; [b setTitleColor:UIColor.whiteColor forState:UIControlStateNormal]; b.titleLabel.font=[UIFont systemFontOfSize:13 weight:UIFontWeightSemibold]; b.backgroundColor=[UIColor colorWithWhite:1 alpha:.09]; b.layer.cornerRadius=7; b.layer.borderWidth=.5; b.layer.borderColor=[UIColor colorWithWhite:1 alpha:.12].CGColor; return b; }
- (UILabel*)label:(NSString*)t size:(CGFloat)z { UILabel*l=[UILabel new]; l.text=t; l.textColor=UIColor.whiteColor; l.font=[UIFont systemFontOfSize:z weight:UIFontWeightSemibold]; return l; }
- (instancetype)initWithFrame:(CGRect)f { if((self=[super initWithFrame:f])) { self.backgroundColor=UIColor.clearColor; self.dump=[NSMutableString new]; [self build]; } return self; }
- (void)build {
 self.panel=[UIView new]; self.panel.backgroundColor=[UIColor colorWithRed:.025 green:.04 blue:.075 alpha:.94]; self.panel.layer.cornerRadius=17; self.panel.layer.borderWidth=1; self.panel.layer.borderColor=[self.blue colorWithAlphaComponent:.45].CGColor; self.panel.clipsToBounds=YES; [self addSubview:self.panel];
 self.header=[UIView new]; [self.panel addSubview:self.header]; UILabel*t=[self label:@"Unity Dumper" size:19]; t.frame=CGRectMake(14,8,220,25); [self.header addSubview:t]; UILabel*sub=[self label:@"IL2CPP runtime metadata" size:10]; sub.textColor=[UIColor colorWithWhite:.68 alpha:1]; sub.frame=CGRectMake(15,32,230,16); [self.header addSubview:sub]; UIButton*x=[self btn:@"â"]; x.frame=CGRectMake(0,8,34,32); x.autoresizingMask=UIViewAutoresizingFlexibleLeftMargin; [x addTarget:self action:@selector(minimize) forControlEvents:UIControlEventTouchUpInside]; [self.header addSubview:x];
 UIButton*d=[self btn:@"Dump"]; d.frame=CGRectMake(12,56,((self.bounds.size.width-36)/2),34); [d addTarget:self action:@selector(runDump) forControlEvents:UIControlEventTouchUpInside]; [self.panel addSubview:d]; UIButton*c=[self btn:@"Copy All"]; c.frame=CGRectMake(CGRectGetMaxX(d.frame)+12,56,d.frame.size.width,34); [c addTarget:self action:@selector(copyAll) forControlEvents:UIControlEventTouchUpInside]; [self.panel addSubview:c];
 self.search=[[UITextField alloc]initWithFrame:CGRectMake(12,98,self.bounds.size.width-24,34)]; self.search.placeholder=@"Filter classes, fields, methodsâ¦"; self.search.textColor=UIColor.whiteColor; self.search.tintColor=self.blue; self.search.font=[UIFont systemFontOfSize:12]; self.search.backgroundColor=[UIColor colorWithWhite:1 alpha:.07]; self.search.layer.cornerRadius=7; self.search.leftView=[[UIView alloc]initWithFrame:CGRectMake(0,0,9,1)]; self.search.leftViewMode=UITextFieldViewModeAlways; [self.search addTarget:self action:@selector(filterChanged) forControlEvents:UIControlEventEditingChanged]; [self.panel addSubview:self.search];
 self.output=[[UITextView alloc]initWithFrame:CGRectZero]; self.output.backgroundColor=[UIColor colorWithWhite:0 alpha:.22]; self.output.textColor=[UIColor colorWithRed:.8 green:.9 blue:1 alpha:1]; self.output.font=[UIFont monospacedSystemFontOfSize:10 weight:UIFontWeightRegular]; self.output.editable=NO; self.output.selectable=YES; [self.panel addSubview:self.output]; self.status=[self label:@"Ready Â· runtime API detection pending" size:10]; self.status.textColor=[UIColor colorWithWhite:.7 alpha:1]; [self.panel addSubview:self.status];
 UIPanGestureRecognizer*p=[[UIPanGestureRecognizer alloc]initWithTarget:self action:@selector(drag:)]; [self.header addGestureRecognizer:p];
}
- (void)layoutSubviews { [super layoutSubviews]; if(!self.minimized){ CGFloat w=MIN(390,self.bounds.size.width-24), h=MIN(590,self.bounds.size.height-50); self.panel.frame=CGRectMake((self.bounds.size.width-w)/2,(self.bounds.size.height-h)/2,w,h); self.header.frame=CGRectMake(0,0,w,50); for(UIView*v in self.header.subviews) if([v isKindOfClass:UIButton.class]) v.frame=CGRectMake(w-46,8,34,32); self.output.frame=CGRectMake(12,140,w-24,h-177); self.status.frame=CGRectMake(12,h-30,w-24,18); } else { self.panel.frame=CGRectMake(0,0,100,38); self.header.frame=self.panel.bounds; self.output.hidden=YES; self.search.hidden=YES; self.status.hidden=YES; for(UIView*v in self.panel.subviews) if(v!=self.header) v.hidden=YES; for(UIView*v in self.header.subviews) if([v isKindOfClass:UILabel.class]) v.hidden=YES; self.mini.hidden=NO; } }
- (void)minimize { self.minimized=!self.minimized; if(self.minimized){ for(UIView*v in self.panel.subviews) if([v isKindOfClass:UIButton.class]||v==self.search||v==self.output||v==self.status) v.hidden=YES; self.panel.backgroundColor=[UIColor colorWithRed:.025 green:.04 blue:.075 alpha:.98]; } else { for(UIView*v in self.panel.subviews) v.hidden=NO; for(UIView*v in self.header.subviews) v.hidden=NO; } [self setNeedsLayout]; }
- (void)drag:(UIPanGestureRecognizer*)g { CGPoint d=[g translationInView:self]; if(g.state==UIGestureRecognizerStateChanged){ CGRect r=self.panel.frame; r.origin.x+=d.x; r.origin.y+=d.y; r.origin.x=MAX(0,MIN(self.bounds.size.width-r.size.width,r.origin.x)); r.origin.y=MAX(0,MIN(self.bounds.size.height-r.size.height,r.origin.y)); self.panel.frame=r; [g setTranslation:CGPointZero inView:self]; } }
- (void)filterChanged { [self renderFiltered]; }
- (void)renderFiltered { NSString*q=self.search.text.lowercaseString?:@""; NSMutableArray*a=[NSMutableArray new]; for(NSString*l in [self.dump componentsSeparatedByString:@"\n"]) if(!q.length||[l.lowercaseString containsString:q]) [a addObject:l]; self.output.text=[a componentsJoinedByString:@"\n"]; }
- (void)runDump { [self endEditing:YES]; [self.dump setString:@""]; self.status.text=@"Inspecting IL2CPP exportsâ¦"; dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED,0),^{
 DomainGet dg=(DomainGet)sym("il2cpp_domain_get"); DomainAssemblies da=(DomainAssemblies)sym("il2cpp_domain_get_assemblies"); AssemblyImage ai=(AssemblyImage)sym("il2cpp_assembly_get_image"); ImageName in=(ImageName)sym("il2cpp_image_get_name"); ImageClassCount cc=(ImageClassCount)sym("il2cpp_image_get_class_count"); ImageClass cl=(ImageClass)sym("il2cpp_image_get_class"); ClassName cn=(ClassName)sym("il2cpp_class_get_name"); ClassNamespace ns=(ClassNamespace)sym("il2cpp_class_get_namespace"); ClassFields cf=(ClassFields)sym("il2cpp_class_get_fields"); FieldName fn=(FieldName)sym("il2cpp_field_get_name"); FieldOffset fo=(FieldOffset)sym("il2cpp_field_get_offset"); FieldType ft=(FieldType)sym("il2cpp_field_get_type"); TypeName tn=(TypeName)sym("il2cpp_type_get_name"); FieldFlags ff=(FieldFlags)sym("il2cpp_field_get_flags"); TypeFree tfree=(TypeFree)sym("il2cpp_free"); ClassMethods cm=(ClassMethods)sym("il2cpp_class_get_methods"); MethodName mn=(MethodName)sym("il2cpp_method_get_name"); MethodParamCount pc=(MethodParamCount)sym("il2cpp_method_get_param_count");
 if(!dg||!da||!ai||!in||!cc||!cl||!cn||!ns||!cf||!fn||!fo||!ft||!tn||!ff||!cm||!mn||!pc){ dispatch_async(dispatch_get_main_queue(),^{ self.status.text=@"IL2CPP exports unavailable in this process"; self.output.text=@"No dump produced. This process may not be a Unity IL2CPP game, exports may be hidden, or the runtime may not be initialized. No offsets were guessed."; }); return; }
 void*domain=dg(); if(!domain){ dispatch_async(dispatch_get_main_queue(),^{self.status.text=@"IL2CPP domain not ready";}); return;} size_t n=0; void**assemblies=da(domain,&n); NSMutableString*out=[NSMutableString new]; NSUInteger gameClasses=0, fields=0, methods=0;
 for(size_t i=0;i<n;i++){ void*image=ai(assemblies[i]); if(!image)continue; NSString*iname=S(in(image)); if(systemAssembly(iname))continue; size_t count=cc(image); for(size_t j=0;j<count;j++){ void*k=cl(image,j); if(!k)continue; NSString*name=S(cn(k)),*space=S(ns(k)); if([name hasPrefix:@"<"]||[name containsString:@"DisplayClass"])continue; gameClasses++; [out appendFormat:@"\n[%@] %@%@\n",iname,[space isEqual:@""]?@"": [space stringByAppendingString:@"."],name]; void*iter=NULL,*field=NULL; while((field=cf(k,&iter))){ const char*raw=tn(ft(field)); NSString*type=raw?S(raw):@"?"; size_t off=fo(field); [out appendFormat:@"  FIELD %@ %@ +0x%zx\n",type,S(fn(field)),off]; fields++; } iter=NULL; void*m=NULL; while((m=cm(k,&iter))){ [out appendFormat:@"  METHOD %@ (%u params)\n",S(mn(m)),pc(m)]; methods++; } } }
 dispatch_async(dispatch_get_main_queue(),^{ [self.dump setString:out]; [self renderFiltered]; self.status.text=[NSString stringWithFormat:@"Done Â· %lu classes Â· %lu fields Â· %lu methods",(unsigned long)gameClasses,(unsigned long)fields,(unsigned long)methods]; if(!gameClasses)self.output.text=@"Runtime API responded, but no non-system assemblies/classes passed the filter. This is not evidence that the game has no classes."; });
 }); }
- (void)copyAll { if(!self.output.text.length){self.status.text=@"Nothing to copy â run Dump first";return;} UIPasteboard.generalPasteboard.string=self.output.text; self.status.text=@"Filtered results copied"; }
@end
static void UnityDumperInstall(void){ dispatch_async(dispatch_get_main_queue(),^{ UIApplication*app=UIApplication.sharedApplication; UIWindow*w=nil; if(@available(iOS 13.0,*)){ for(UIScene*s in app.connectedScenes) if(s.activationState==UISceneActivationStateForegroundActive&&[s isKindOfClass:UIWindowScene.class]) for(UIWindow*x in ((UIWindowScene*)s).windows) if(x.isKeyWindow){w=x;break;} } if(!w)w=app.keyWindow; if(!w)return; for(UIView*v in w.subviews)if([v isKindOfClass:UnityDumper.class])return; UnityDumper*u=[[UnityDumper alloc]initWithFrame:w.bounds]; u.autoresizingMask=UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleHeight; [w addSubview:u]; }); }
__attribute__((constructor)) static void UnityDumperEntry(void){ dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(2*NSEC_PER_SEC)),dispatch_get_main_queue(),^{UnityDumperInstall();}); }